# Generated by Django 3.2.16 on 2023-01-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230127_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpeg 파일을 업로드해주세요.', upload_to='accounts/avater/%Y/%m/%d'),
        ),
    ]
